### ISSUE TITLE
Roadmap to β(0.1.0) release

### ISSUE THREAD

**Issue by awrznc** [awrznc/rust-connpass#2]
## Todo

- [x] Write test
- [x] Write logic
   - [x] http request
      - [x] path only
      - [x] set query params
      - [x] add user agent
   - [x] mock
   - [x] response struct
- [x] Write README.md
- [x] Write Examples
- [x] Write docs
- [x] Publishing to Crates.io

**Comment by awrznc** [comment]
## Create a NOT List

### Out of scope

(Nothing for now.)

### Unresolved (maybe next scope)

* set user agent
* response
   * url
   * headers
* async
* mock handler
* output html file
* output raw json string

**Comment by awrznc** [comment]
corresponded to #6
